apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: demis
  name: demis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demis
  template:
    metadata:
      labels:
        app: demis
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}" 
        name: flaskapi
