apiVersion: v1
kind: Service
metadata:
  name: demis-svc
  labels:
    app: demis
spec:
  selector:
    app: demis
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
    
